# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade479a8c88b9c8ab361cf6afadf6253ae9c8b03caa1ac82e35deddece6974abfa1d086d7a2959369cf84e449c3590da1de82195003139f61b5128faa37c42b8

test:
  secret_key_base: 0efc1aca9abb275d32a0a1d586d76ab117213f68b751d8ba3803715bd9286344edfc9b00001e1a2f94ced6e14bc5aac00b386d722cee22209380999a5a27736d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
