User.create(username: 'admin', password:'123' , admin_type: 'true')
User.create(username: 'Group', firstname:'The', lastname: 'Group', email: 'Group14@gmail.com', password:'14' , admin_type: 'true')
User.create(username: 'CoolDude123', firstname:'Billy', lastname: 'Joe', email: 'Billy_Joe@gmail.com', password:'123' , admin_type: 'false')
User.create(username: 'NiceGuy', firstname:'Bobby', lastname: 'Jean', email: 'Nice_Jeans@gmail.com', password:'123' , admin_type: 'false')
User.create(username: 'Random', firstname:'Guy', lastname: 'Fieri', email: 'Spikey.hair@gmail.com', password:'123' , admin_type: 'false')